//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SpamDog.rc
//
#define IDS_MAINFRM_TRASH               1
#define IDD_SPAMDOG_DIALOG              102
#define IDD_MSGFRM_DIALOG               103
#define IDD_SETUPFRM_DIALOG             104
#define IDD_SYSSETUPFRM_DIALOG          106
#define IDD_RULESETUPFRM_DIALOG         107
#define IDD_RULEEDITFRM_DIALOG          108
#define IDD_MAPIFOLDER_DIALOG           109
#define IDD_ABOUTTHIS_DIALOG            110
#define IDD_LIVEUPDATE_DIALOG           111
#define IDD_LEARNWIZ_DIALOG             112
#define IDD_WIZARD_DIALOG               113
#define IDD_MSGSETUPFRM_DIALOG          114
#define IDD_SCANSETUPFRM_DIALOG         115
#define IDD_OTHERSETUPFRM_DIALOG        116
#define IDD_WEBFRM_DIALOG               117
#define IDD_MAILREPORTFRM_DIALOG        119
#define IDD_REPORTFRM_DIALOG            120
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       129
#define IDB_BITMAP1                     130
#define IDB_BITMAP2                     131
#define IDR_MENU1                       133
#define IDB_BITMAP3                     134
#define IDB_FOLDERLIST                  135
#define IDB_BITMAP4                     136
#define IDB_BITMAP5                     137
#define IDB_BITMAP6                     138
#define IDB_BITMAP7                     144
#define IDI_ICON2                       146
#define IDD_WIZ_MAILEXPERT              148
#define IDD_WIZ_RULE                    149
#define IDD_WIZ_FOLDERLEARN             150
#define IDD_WIZ_PASSPORT                151
#define IDI_ICON3                       152
#define IDB_BITMAP8                     155
#define IDD_WIZ_TRACER                  156
#define IDI_ICON4                       161
#define IDI_ICON5                       162
#define IDB_BITMAP9                     169
#define IDB_BITMAP10                    170
#define IDD_PROPPAGE_GETDOGID           172
#define IDD_PROPPAGE_WELCOME            173
#define IDD_PROPPAGE_SETOUTLOOK         174
#define IDD_PROPPAGE_SETEMAILIDENT      175
#define IDD_PROPPAGE_WAITMAILIDENT      176
#define IDD_PROPPAGE_DONE               177
#define IDD_PROPPAGE_LEARNTEST          178
#define IDD_PROPPAGE_OTHER              179
#define IDR_MENU2                       180
#define IDB_BITMAP11                    181
#define IDC_BUTTON1                     1000
#define IDC_BUTTON2                     1001
#define IDC_BUTTON13                    1002
#define IDC_EDIT2                       1003
#define IDC_BUTTON16                    1003
#define IDC_STATIC2                     1004
#define IDC_BUTTON14                    1004
#define IDC_STATIC3                     1005
#define IDC_EDIT1                       1006
#define IDC_COMBO2                      1006
#define IDC_EDIT_BIGMAIL                1006
#define IDC_EDIT_EMAILLIST              1006
#define IDC_EDIT_AUTOSHOWREPORT         1006
#define IDC_STATIC4                     1007
#define IDC_CHECK7                      1007
#define IDC_EDIT3                       1008
#define IDC_STATIC_WIZ                  1008
#define IDC_EDIT_RBL2                   1008
#define IDC_BUTTON3                     1009
#define IDC_MAILEXP_STATIC              1009
#define IDC_BUTTON4                     1010
#define IDC_EXP_PROGRESS1               1010
#define IDC_BUTTON5                     1011
#define IDC_BUTTON6                     1012
#define IDC_STATIC_TIME                 1012
#define IDC_BUTTON7                     1013
#define IDC_PROGRESS1                   1013
#define IDC_BUTTON8                     1014
#define IDC_BUTTON9                     1015
#define IDC_STATIC_MEMO                 1015
#define IDC_STATIC5                     1016
#define IDC_CHECK_MAILTRACER            1016
#define IDC_BUTTON10                    1017
#define IDC_EDIT_TRACERTIME             1017
#define IDC_EDIT_TRACEREXPIRE           1017
#define IDC_LIST1                       1018
#define IDC_CHECK_STARTWITHAP           1018
#define IDC_EDIT_ARRANGEFOLDER          1019
#define IDC_CHECK_SHOWMSG               1020
#define IDC_BUTTON11                    1021
#define IDC_STATIC_VERSIONNOW           1021
#define IDC_BUTTON12                    1022
#define IDC_STATIC_APLASTUPDATE         1022
#define IDC_STATIC1                     1023
#define IDC_STATIC_DATALASTUPDATE       1023
#define IDC_CHECK1                      1024
#define IDC_TAB1                        1025
#define IDC_CHECK_SYSAUTODEL            1025
#define IDC_SLIDER1                     1026
#define IDC_SLIDER_CUTDB                1026
#define IDC_EDIT_SYSDELDAY              1026
#define IDC_SLIDER_MAXATTSIZE           1026
#define IDC_SLIDER2                     1027
#define IDC_SLIDER_MSGSPEED             1027
#define IDC_CHECK_AUTHEX                1027
#define IDC_SLIDER3                     1028
#define IDC_SLIDER_MSGDELAY             1028
#define IDC_STATIC_DOGID                1028
#define IDC_CHECK_AUTODEL               1029
#define IDC_COLORBOX_OK                 1030
#define IDC_STATIC_LICENSED             1030
#define IDC_COLORBOX_SENDER             1031
#define IDC_COLORBOX_PREVIEW            1031
#define IDC_EDIT_DNS                    1031
#define IDC_COLORBOX_XX                 1032
#define IDC_EDIT_IPKEY                  1032
#define IDC_COLORBOX_SPAM               1033
#define IDC_COLORBOX_VR                 1034
#define IDC_CHECK2                      1034
#define IDC_CHECK_AUTOUPDATE            1034
#define IDC_EDIT_RBL1                   1034
#define IDC_CHECK3                      1035
#define IDC_COLORBOX_TEXT               1035
#define IDC_CHECK_SPAMADDRESS           1035
#define IDC_BUTTON15                    1036
#define IDC_CHECK_IPIDENT               1036
#define IDC_COMBO1                      1037
#define IDC_EXPLORER1                   1037
#define IDC_RADIO1                      1038
#define IDC_STATICS                     1038
#define IDC_RADIO2                      1039
#define IDC_CHECK_NODOGNEWS             1039
#define IDC_RADIO3                      1040
#define IDC_CHECK_IPSTRIDENT            1040
#define IDC_RADIO4                      1041
#define IDC_STATIC_MAXATTSIZE           1041
#define IDC_CHECK_REPORTWITHDEL         1042
#define IDC_LIST_MAIL                   1043
#define IDC_CHECK_DELSPAM               1044
#define IDC_CHECK4                      1045
#define IDC_CHECK_NULLCONTENT           1045
#define IDC_CHECK_STOPREPORT            1045
#define IDC_CHECK_NEEDREPORT            1045
#define IDC_STATIC_COUNTER              1045
#define IDC_TREE1                       1046
#define IDC_STATIC_MAIN                 1046
#define IDC_STATICFOLDER                1047
#define IDC_COMBO_OLTYPE                1047
#define IDC_CHECK5                      1048
#define IDC_CHECK_BOOTSTART             1048
#define IDC_STATIC_STATUS               1049
#define IDC_CHECK6                      1050
#define IDC_CHECK_SPAMSUBJECT           1050
#define IDC_STATIC_TEXT                 1050
#define IDC_FILEEDIT                    1051
#define IDC_CHECK_BADSHOW               1052
#define IDC_TAB2                        1052
#define IDC_SLIDER_UNKNOWNRATE          1053
#define IDC_CHECK_NULLSENDER            1054
#define IDC_CHECK_NULLSUBJECT           1055
#define IDC_CHECK_AUTOBACKUP            1056
#define IDC_CHECK_AUTOSHOWREPORT        1056
#define IDC_STATIC_DELAYVALUE           1057
#define IDC_STATIC_AUTOREPORTTEXT       1057
#define IDC_STATIC_SPEEDVALUE           1058
#define IDC_STATIC_UNKNOWNVALUE         1059
#define IDC_STATIC_CUTVALUE             1060
#define ID_MENUITEM32771                32771
#define ID_MENUITEM32772                32772
#define ID_MENUITEM32773                32773
#define ID_MENUITEM32774                32774
#define ID_MENUITEM32775                32775
#define ID_MENUITEM32776                32776
#define ID_MENUITEM32777                32777
#define ID_MENUITEM32778                32778
#define ID_MENUITEM32779                32779
#define ID_MENUITEM32780                32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        182
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           121
#endif
#endif
